
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paula
 */
public class MenuCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form MenuCalculadora
     */
    public MenuCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        parcialUno = new javax.swing.JTextField();
        parcialDos = new javax.swing.JTextField();
        terceraNota = new javax.swing.JTextField();
        setentaPorciento = new javax.swing.JTextField();
        examenFinal = new javax.swing.JTextField();
        definitiva = new javax.swing.JLabel();
        calcularTerceraNota = new javax.swing.JButton();
        calcularSetentaPorciento = new javax.swing.JButton();
        calcularTreintaPorciento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        jLabel1.setText("Calculadora Academica ");

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel2.setText("Parcial Uno");

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel3.setText("Parcial Dos");

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel4.setText("Tercera Nota");

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel5.setText("Setenta %");

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel6.setText("Examen Final");

        parcialUno.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        parcialDos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        terceraNota.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        terceraNota.setEnabled(false);

        setentaPorciento.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        examenFinal.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        definitiva.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N

        calcularTerceraNota.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        calcularTerceraNota.setText("Calcular Tercera Nota");
        calcularTerceraNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularTerceraNotaActionPerformed(evt);
            }
        });

        calcularSetentaPorciento.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        calcularSetentaPorciento.setText("Calcular Setenta %");
        calcularSetentaPorciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSetentaPorcientoActionPerformed(evt);
            }
        });

        calcularTreintaPorciento.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        calcularTreintaPorciento.setText("Calcular Treinta %");
        calcularTreintaPorciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularTreintaPorcientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setentaPorciento)
                            .addComponent(terceraNota)
                            .addComponent(parcialDos)
                            .addComponent(parcialUno)
                            .addComponent(examenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calcularTerceraNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcularSetentaPorciento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calcularTreintaPorciento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(definitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(parcialUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(parcialDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(terceraNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(calcularTerceraNota)))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setentaPorciento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calcularSetentaPorciento)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(examenFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calcularTreintaPorciento)))
                .addGap(41, 41, 41)
                .addComponent(definitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularSetentaPorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSetentaPorcientoActionPerformed
        if(parcialUno.getText().equals("")||parcialDos.getText().equals("")||terceraNota.getText().equals("")){
           JOptionPane.showMessageDialog(rootPane,"Todos los Campos son Obligatorios");
       }else
        setentaPorciento.setText(
               String.valueOf(
            (Float.parseFloat(parcialUno.getText())+
               Float.parseFloat(parcialDos.getText())+
               Float.parseFloat(terceraNota.getText()))
                       /3*0.7));
    }//GEN-LAST:event_calcularSetentaPorcientoActionPerformed

    private void calcularTerceraNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularTerceraNotaActionPerformed
     float numeroNotas=Float.parseFloat(JOptionPane.showInputDialog("Cuantas notas se valoraran:"));
     float notas=0;
     for(int i=0;i<numeroNotas;i++){
         notas+=Float.parseFloat(JOptionPane.showInputDialog("Valor Nota:"+(i+1)));
     }
     terceraNota.setText(
     String.valueOf(
     notas/numeroNotas
     )
     );
    }//GEN-LAST:event_calcularTerceraNotaActionPerformed

    private void calcularTreintaPorcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularTreintaPorcientoActionPerformed
        examenFinal.setText(
                String.valueOf(
                       
        Float.parseFloat(JOptionPane.showInputDialog("Valor Examen Final"))*0.3));
        definitiva.setText(
                String.valueOf(
        Float.parseFloat(setentaPorciento.getText())+Float.parseFloat(examenFinal.getText())));
    }//GEN-LAST:event_calcularTreintaPorcientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularSetentaPorciento;
    private javax.swing.JButton calcularTerceraNota;
    private javax.swing.JButton calcularTreintaPorciento;
    private javax.swing.JLabel definitiva;
    private javax.swing.JTextField examenFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField parcialDos;
    private javax.swing.JTextField parcialUno;
    private javax.swing.JTextField setentaPorciento;
    private javax.swing.JTextField terceraNota;
    // End of variables declaration//GEN-END:variables
}
